# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\basketballStats.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(581, 568)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.player_label = QtWidgets.QLabel(self.centralwidget)
        self.player_label.setGeometry(QtCore.QRect(30, 30, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setStrikeOut(False)
        self.player_label.setFont(font)
        self.player_label.setObjectName("player_label")
        self.player = QtWidgets.QTextEdit(self.centralwidget)
        self.player.setGeometry(QtCore.QRect(30, 90, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setStrikeOut(False)
        self.player.setFont(font)
        self.player.setObjectName("player")
        self.search_player = QtWidgets.QPushButton(self.centralwidget)
        self.search_player.setGeometry(QtCore.QRect(400, 90, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.search_player.setFont(font)
        self.search_player.setObjectName("search_player")
        self.noplayer_label = QtWidgets.QLabel(self.centralwidget)
        self.noplayer_label.setGeometry(QtCore.QRect(30, 140, 350, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.noplayer_label.setFont(font)
        self.noplayer_label.setText("")
        self.noplayer_label.setObjectName("noplayer_label")
        self.get_statistics = QtWidgets.QPushButton(self.centralwidget)
        self.get_statistics.setGeometry(QtCore.QRect(140, 410, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStrikeOut(False)
        self.get_statistics.setFont(font)
        self.get_statistics.setObjectName("get_statistics")
        self.team_label = QtWidgets.QLabel(self.centralwidget)
        self.team_label.setGeometry(QtCore.QRect(30, 180, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setStrikeOut(False)
        self.team_label.setFont(font)
        self.team_label.setObjectName("team_label")
        self.team = QtWidgets.QTextEdit(self.centralwidget)
        self.team.setGeometry(QtCore.QRect(30, 240, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setStrikeOut(False)
        self.team.setFont(font)
        self.team.setObjectName("team")
        self.search_team = QtWidgets.QPushButton(self.centralwidget)
        self.search_team.setGeometry(QtCore.QRect(400, 240, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.search_team.setFont(font)
        self.search_team.setObjectName("search_team")
        self.noteam_label = QtWidgets.QLabel(self.centralwidget)
        self.noteam_label.setGeometry(QtCore.QRect(30, 290, 400, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.noteam_label.setFont(font)
        self.noteam_label.setText("")
        self.noteam_label.setObjectName("noteam_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 581, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.player_label.setText(_translate("MainWindow", "მოთამაშის სახელი და გვარი:"))
        self.player.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.search_player.setText(_translate("MainWindow", "ძებნა"))
        self.get_statistics.setText(_translate("MainWindow", "გუნდების სტატისტიკა"))
        self.team_label.setText(_translate("MainWindow", "გუნდის სახელი:"))
        self.team.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.search_team.setText(_translate("MainWindow", "ძებნა"))
